### ISSUE TITLE
Non-deterministic Position values when subscribing to All Streams.

### ISSUE THREAD

**Issue by larsw** [damianh/SqlStreamStore#31]
As briefly discussed on https://ddd-cqrs-es.slack.com/messages/sql-stream-store/ :

With the isolation level set to _READ COMMITTED_, the **Position** values are non-deterministic in the sense that with two or more concurrent write operations can end up with creating "holes" in the Position sequence if one of the operation fails. This in turn affects the reads against the table; it is impossible to know if all new events are being picked up by the poller without keeping a state per subscriber / stream.

I assume that the intention of **SqlStreamStore** is to be able to use _READ COMMITTED_ as the isolation levell; _SERIALIZABLE_ reads and writes against the Streams table will probably result in a very poor performance.

**Comment by yreynhout** [comment]
Beware if you run on Sql Azure, since the isolation level is not going to protect you - http://stackoverflow.com/questions/20442543/sql-server-strange-identity-increment

**Comment by oguzhaneren** [comment]
NEventStore implement https://github.com/NEventStore/NEventStore/blob/develop/src/NEventStore/Client/CommitSequencer.cs for that

**Comment by davoad** [comment]
The same discussion in relation to NEventStore is also here: http://dba.stackexchange.com/questions/133556/can-i-rely-on-reading-sql-server-identity-values-in-order

The conclusion seems to be that there is a small window between the generation of the new Identity and the start of the transaction (and the time the key lock is taken) so another write operation could start and end in this window, meaning that the second event could be read before the first. I don't think a _serializable_ isolation level will help if this is true. 

In fact, these issues are _Open_ for NEventStore and the first issue has a [comment](https://github.com/NEventStore/NEventStore/issues/425#issuecomment-211069101) asking if this project has solved the issue.

https://github.com/NEventStore/NEventStore/issues/425
https://github.com/NEventStore/NEventStore.Persistence.SQL/issues/21

**Comment by damianh** [comment]
Thanks for the links @yreynhout @oguzhaneren @davoad !

@larsw Reading the links it appears that setting the isolation level to `serializable` is not going to help.

In `SqlStreamStore` the way the poller works is by checking for the (`HeadPosition`)[https://github.com/damianh/SqlStreamStore/blob/master/src/SqlStreamStore/Subscriptions/PollingStreamStoreNotifier.cs] and then it "signals" to each subscribers who each perform an independent read operations (`ReadAllForwards`, `ReadStreamForwards`). (There are synchronization mechanisms in place to ensure a subsriber is doing a single read at a time, regardless of how many "singals" are raised").

I think this reduces the chance of the issue occurring but I don't think it eliminates it.

SqlStreamStore also allows event and stream deletion so gaps are expected, thus knowing if a gap is because of sequence out of order or because of deletion is going to be tricky.

HMMM

**Comment by damianh** [comment]
Marten is postgres only so interesting that it happens there too.

**Comment by damianh** [comment]
> Since the async daemon was inevitably going to use some sort of polling (NOTIFY/LISTEN in Postgresql was not adequate by itself)

Interesting to know...

**Comment by damianh** [comment]
Opened a PR that takes a similar approach to Marten https://github.com/damianh/SqlStreamStore/pull/39 . Not sure how to go about deterministically testing this. Also am tired. Please take a look at let me know what you think.
